language: java
script: gradle dist

install:
- echo sonatypeUsername=none >> gradle.properties
- echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: bPE48+2+IlSPBB+GN32hCYitqnPq7kW6tWZXYeBwI0M6ByPcsy+DbyRslfdUffAOpjHj2w0EutWJqjUhsHuKhcR2KU++UILZsV7henq3I6PXF4OmaU7wr6NtRrBA5CP42wommbSO1Qdk2Gqk7uwrHS+XrW9MmeFPePWguImw20g=
  file:
    - build/distributions/xmlcalabash1-xcc-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true

